#
# Spring Properties
#
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/turbodepot_api?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: devuser
    password: devpassword
    driver-class-name: org.mariadb.jdbc.Driver
